apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: 0.24.0
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: alertmanager
  type: ClusterIP  
  ports:
    - port: 9093
      targetPort: 9093
