apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: monitoring
    name: prom-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv-claim
  namespace: monitoring
spec:
  storageClassName: slow
  volumeName: prom-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi